# Generated by Django 4.1.5 on 2023-01-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                height_field=200, null=True, upload_to="covers", width_field=100
            ),
        ),
    ]
