# Generated by Django 4.1.5 on 2023-01-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, height_field=200, upload_to="covers/", width_field=100
            ),
        ),
    ]
