# Generated by Django 4.1.5 on 2023-02-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(default="covers/Book", upload_to="covers/"),
        ),
    ]
