# Generated by Django 4.1.5 on 2023-02-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_book_author"),
        ("cart", "0002_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(blank=True, null=True, to="catalog.book"),
        ),
    ]
